[project]
name = "gcp-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
   "google-cloud-aiplatform",
   "ipykernel>=6.29.5",
   "langchain-google-vertexai>=2.0.24",
   "pydantic==2.9.0",
   "ragstack-ai",
]
